[package]
name = "infra"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace dependencies
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true
config.workspace = true
dotenvy.workspace = true

redis.workspace = true
lettre.workspace = true
tokio.workspace = true

# Internal crates
domain.workspace = true
common.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
