[package]
name = "service-auth"
version.workspace = true
edition.workspace = true

[dependencies]
# Workspace dependencies
async-trait.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true
jsonwebtoken.workspace = true
argon2.workspace = true
validator.workspace = true
rand = "0.8"

# Internal crates
domain.workspace = true
common.workspace = true
infra.workspace = true
