[package]
name = "service-audit"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
domain = { path = "../domain" }
common = { path = "../common" }
chrono = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
actix-web = { workspace = true }
sqlx = { workspace = true }