[package]
name = "service-tool"
version.workspace = true
edition.workspace = true

[dependencies]
# Workspace dependencies
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true

# Internal crates
domain.workspace = true
common.workspace = true
